# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

variables:
- name: clientDir
  value: $(System.DefaultWorkingDirectory)/ClientApp/RetroArcadeMachines

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    cd ${{variables.clientDir}}
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/ClientApp/RetroArcadeMachines/dist/RetroArcadeMachines'
    includeRootFolder: false
    archiveType: zip
    archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
    ArtifactName: 'drop'
    publishLocation: Container