name: Build and deploy dotnet core app to Azure Function App - RetroArcadeMachinesAzureFunctionsRead20210430055312

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'Src/AzureFunctions/RetroArcadeMachines.AzureFunctions.Read/RetroArcadeMachines.AzureFunctions.Read.csproj'
  DOTNET_VERSION: '3.1.x'

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'RetroArcadeMachinesAzureFunctionsRead20210430055312'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B43B2C58BFAB4853A824EE8E0CF9E802 }}
